Ctrl+Alt+Shift+Up add volume 5
Ctrl+Alt+Shift+Down add volume -5
Ctrl+Alt+Shift+Left seek -3
Ctrl+Alt+Shift+Right seek  3
Ctrl+Alt+Shift+Space cycle pause
Left frame-back-step
Right frame-step
Enter screenshot
shift+enter screenshot each-frame
s cycle sub-visibility
S cycle sub-visibility
# a cycle-values video-aspect "16:9" "4:3" "2:1" "2.21:1" "1.6:1"
