# ==========    GENERAL    ==========
profile=high-quality
vo=gpu-next
gpu-api=vulkan
fullscreen=no
keepaspect=no
force-seekable=no
keep-open=no
reset-on-next-file=pause
dither-depth=8
scale-antiring=0.6
terminal=no
shuffle=no
save-position-on-quit=no
ontop=no
stop-screensaver=yes
keepaspect-window=yes
window-minimized=no
window-maximized=yes
ab-loop-count=0
screenshot-directory="~/Pictures/Screenshots/shim/"
screenshot-template="%00n"
screenshot-high-bit-depth=yes
screenshot-format=png
screenshot-png-compression=1
geometry=1920x1080+0+1080
# framedrop=no

# ==========    SCALERS AND SHADERS    ==========
glsl-shader="~~/shaders/NVScaler.glsl"
gpu-shader-cache-dir='~~/shaders/cache'
scale=ewa_lanczossharp
dscale=mitchell
cscale=ewa_lanczossharp

# ==========    DEBANDING    ==========
deband=no
deband-iterations=2
deband-threshold=64
deband-range=17
deband-grain=12

# ==========    SUBTITLES & LANGUAGE PRIORITY    ==========
sub-visibility=no
sub-ass=no
sub-ass-override=strip
embeddedfonts=no
sub-font='Netflix Sans'
sub-font-size=40
sub-color='	#ffded302'
sub-border-color='#FF000000'
sub-border-size=2.0
sub-border-style=outline-and-shadow
# sub-border-style=background-box
# sub-border-style=opaque-box
sub-back-color="#A0000000"
sub-shadow-color="#A0000000"
sub-shadow-offset=0.75
sub-spacing=0.0
sub-bold=y
alang=en,eng,ja,jp,jpn
slang=en,eng

# ==========    ON SCREEN DISPLAY AND ON SCREEN CONTROLLER    ==========
osc=yes
border=yes
cursor-autohide-fs-only=yes
cursor-autohide=2500
osd-level=0
osd-bar=no
osd-duration=2500
osd-font='SF-Pro'
osd-font-size=50
osd-color='#FFFFFF'
osd-border-color='#000000'
osd-border-size=1.0
osd-blur=0.0
osd-margin-y=0
osd-margin-x=0

# ==========    AUDIO    ==========
volume=50.0
volume-max=130.0
