LEFT playlist-prev
RIGHT playlist-next
MBTN_LEFT playlist-prev
MBTN_RIGHT playlist-next
SPACE cycle pause
L cycle-values loop-file "inf" "no"
l cycle-values loop-file "inf" "no"
Up frame-step
Down frame-back-step
ENTER screenshot
shift+enter screenshot each-frame
Ctrl+Alt+Shift+Left seek -3
Ctrl+Alt+Shift+Right seek  3
Ctrl+Alt+Shift+Space cycle pause
