# Check the following link for mpv's default keybindings:
# https://github.com/mpv-player/mpv/blob/master/etc/input.conf

# ==========    CUSTOM KEYBINDINGS    ==========

LEFT playlist-prev
RIGHT playlist-next
MBTN_LEFT playlist-prev
MBTN_RIGHT playlist-next
SPACE cycle pause
L cycle-values loop-file "inf" "no"
l cycle-values loop-file "inf" "no"

# ==========    UNBIND    ==========
UP ignore
DOWN ignore
