# ==========    GENERAL    ==========
fullscreen=yes
taskbar-progress=no
force-seekable=no
keep-open=no
reset-on-next-file=pause
terminal=no
shuffle=yes
ontop=yes
ontop-level=system
border=yes
keepaspect-window=yes
stop-screensaver=yes
window-minimized=no
window-maximized=yes
ab-loop-count=0
loop-playlist=inf

# ==========    OSD    ==========
osd-bar=no
osc=no
border=yes
cursor-autohide-fs-only=yes
cursor-autohide=1000
osd-level=1
osd-duration=1000
hr-seek=yes
osd-font='SF Pro Regular'
osd-font-size=50
osd-color='#FFFFFF'
osd-border-color='#000000'
osd-border-size=0.6
osd-blur=0.2
osd-margin-y=325
osd-margin-x=0

# ==========    AUDIO    ==========
mute=yes
volume=0
volume-max=100.0
