# Default configs

# fps for output (can be -1 for source fps).
fps=-1

# Width of the resulting gif.
width=-1

# Leave -1 to automatically determine height or set to customize.
height=-1

# File extension (e.g. mp4 for telegram gifs).
extension=mp4

# Gif output directory. It supports mpv expansions: https://mpv.io/manual/master/#paths
outputDirectory="/home/soders/Pictures/Screenshots/mpv/"

# Set mode use to work with. Available 'gif', 'video' and 'all'.
mode=gif
